### PR TITLE
New Hebrew he.json file

### PR DESCRIPTION
**Pull request by nadavkav**
Hello H5P translation team,
Please see if you can integrate a new Hebrew he.json file into the h5p-editor-interactive-video
Best,
Nadav

### CODE REVIEW

**Comment by nadavkav** [comment]
Hi @timothyylim ,
Please see if you can merge this.
Best,
Nadav

**Comment by timothyylim** [comment]
Hi @nadavkav , since your original PR a few strings have been added. If you could update your translation, I'll merge it in right away. Thank you!

**Comment by nadavkav** [comment]
Hi @timothyylim , I have updated the PR with the new strings.

Thank you for integrating all the other PRs too!

**Comment by timothyylim** [comment]
Thank you :) It'll be part of the next release!

**Comment by nadavkav** [comment]
Thanks!

@timothyylim , I wonder...
Does H5P components get their own releases? or do I have to wait for all the Hebrew translations that got merged this week, until the official H5P-moodle-plugin release?

**Comment by timothyylim** [comment]
@nadavkav, content types are released on a rolling basis and will be available for updates via the H5P Hub. If the content types aren't under development and all that has changed are language files, they should be released immediately. If they are under development they will be released when all dev work is done.

Translations for the specific plugins will be released with each release of the plugin (much lower cadence than content types).

**Comment by nadavkav** [comment]
Thanks! now it is perfectly clear :smile:

**Pull request merged**
